version: '2'

services:
  helpy:
#    image: helpy/helpy
    build: .
    restart: always
    volumes:
      - rails-assets:/helpy/public
    env_file: docker/.env
    environment:
      - DO_NOT_PREPARE=true
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8990:8080"
  postgres:
    image: postgres:9.4
    restart: always
    env_file: docker/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  rails-assets:
    driver: local
